name: webi
description: Dart Learning
version: 0.0.1
author: Charleno Pires

environment:
  sdk: '>=2.0.0-dev.46.0 <=2.0.0-dev.50.0'

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
